services:
  bot-worker:
    build:
      context: .
      dockerfile: apps/bot-worker/Dockerfile
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - BOT_CONCURRENCY=1
      - NODE_ENV=production
      - BOT_HEADLESS=false
      - BOT_DEBUG=false
    shm_size: '4gb'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 7G
    ports:
      - "8765:8765"
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
